language: c

cache:
  directories:
    - github-cache
    - pharo-local

matrix:
  include:
    - env: JOB=bootstrap BOOTSTRAP_ARCH=32 PHARO_VERSION=60

addons:
  apt:
    packages:
    - libasound2:i386
    - libssl1.0.0:i386
    - libfreetype6:i386
    - libcairo2:i386

script:
- bash ./bootstrap/scripts/bootstrap.sh
- ./bootstrap-cache/vm/pharo bootstrap-cache/Pharo.image test --no-xterm --fail-on-failure ".*"